sudo apt update
sudo apt install -y gdebi-core
sudo apt install -y make 
sudo apt install -y libpng-dev 
sudo apt install -y tcl 
sudo apt install -y tk 
sudo apt install -y tk-dev 
sudo apt install -y tk-table 
sudo apt install -y default-jdk 
sudo apt install -y libxml2-dev 
sudo apt install -y git 
sudo apt install -y libssl-dev  
sudo apt install -y libcurl4-openssl-dev 
sudo apt install -y libjpeg-dev 
sudo apt install -y imagemagick 
sudo apt install -y libmagick++-dev 
sudo apt install -y gsfonts 
sudo apt install -y unixodbc-dev 
sudo apt install -y zlib1g-dev 
sudo apt install -y libfreetype6-dev 
sudo apt install -y libfribidi-dev 
sudo apt install -y libharfbuzz-dev 
sudo apt install -y libicu-dev 
sudo apt install -y libmysqlclient-dev 
sudo apt install -y libgeos-dev 
sudo apt install -y libudunits2-dev 
sudo apt install -y libfontconfig1-dev 
sudo apt install -y libcairo2-dev 
sudo apt install -y libtiff-dev 
sudo apt install -y libgdal-dev 
sudo apt install -y gdal-bin 
sudo apt install -y libproj-dev 
sudo apt install -y libssh2-1-dev 
sudo apt install -y python3 
sudo apt install -y perl 
sudo apt install -y libv8-dev 
sudo apt install -y cmake 
sudo apt install -y libsodium-dev 
sudo apt install -y libglu1-mesa-dev 
sudo apt install -y libgl1-mesa-dev 
sudo apt install -y libglpk-dev 
sudo apt install -y libgmp3-dev
sudo apt install -y libdbi1 
sudo apt install -y libev-dev 
sudo apt install -y libev4 
sudo apt install -y librrd8 
sudo apt install -y rrdtool
sudo apt install -y lib32gcc-s1 
sudo apt install -y lib32stdc++6 
sudo apt install -y libc6-i386 
sudo apt install -y libclang-10-dev 
sudo apt install -y libclang-common-10-dev 
sudo apt install -y libclang-dev 
sudo apt install -y libclang1-10 
sudo apt install -y libgc1c2 
sudo apt install -y libllvm10 
sudo apt install -y libobjc-9-dev 
sudo apt install -y libobjc4 
